Make typescript optional peer dependency
ajafff/tsutils pull request #118
Opened 2020-04-23 11:19 UTC by sheerun

This is to prevent warning when tsutils is required by other packages as optional dependency, for example: `warning "prettierx > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".`

2020-09-06 13:38 UTC, Trackhe reviewed
It is not optional..

2020-09-06 13:39 UTC, Trackhe requested changes
It is not optional..

2020-09-06 14:51 UTC, closed without merging

2021-04-22 17:07 UTC, codyrobbins commented
For anyone else with this problem:

* https://github.com/typescript-eslint/typescript-eslint/issues/1287
* https://github.com/jest-community/eslint-plugin-jest/issues/601

2021-04-23 11:58 UTC, ajafff commented
for posterity: I don't know why people would install this package without also installing TypeScript. See https://github.com/ajafff/tsutils/issues/134#issuecomment-825607176

2021-04-23 13:59 UTC, codyrobbins commented
@ajafff Because they don’t choose to install it, it gets pulled in via a dependency chain. For example, if you install [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) to use ESLint with Jest then you perpetually get this warning despite having no need for Typescript.